# Generated by Django 4.0.10 on 2023-06-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('f', 'food'), ('nf', 'non-food')], max_length=20),
        ),
    ]
